#!/usr/bin/env python3


import os
import subprocess
import sys
import mysql.connector
import socket
import threading
import time
import json

		

def get_one(s,reponame,branch='master'):
	data = {}
	data['command'] = 'checkout'
	data['reponame'] = reponame
	data['commit'] = branch 
	jsondata = json.dumps(data)
	s.send(jsondata.encode('utf-8'))
	resp = s.recv(5000)

def send_message(jsondata=''):
	getipsock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
	getipsock.connect(("gmail.com",80))
	myipaddress = str(getipsock.getsockname()[0])
	getipsock.close()

	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	s.connect((myipaddress,19999))

	get_one(s,'testdevel')
	get_one(s,'auroranotifier-server')


	data = {}
	data['command'] = 'wait'
	jsondata = json.dumps(data)
	s.send(jsondata.encode('utf-8'))

	resp = s.recv(5000)
	recv_jsondata = json.loads(resp.decode('utf-8'))
	print(recv_jsondata)
	if 'symlinks' in recv_jsondata:
		for symlink in recv_jsondata['symlinks']:
			if 'symlink'  in symlink:
				localpath = "ip/%s" % (symlink['reponame'])
				os.system("""
mkdir -p %s
cd %s
ln -sfT %s %s
""" % (os.path.dirname(localpath),os.path.dirname(localpath),symlink['symlink'],os.path.basename(localpath)))

	data = {}
	data['command'] = 'exit'
	jsondata = json.dumps(data)
	s.send(jsondata.encode('utf-8'))
	resp = s.recv(10)

	s.close()


#if len(sys.argv) < 2:
#	print("Missing arguments")
#	sys.exit(-1)
#elif len(sys.argv) == 2:
#	branch = "master"
#else:
#	branch = sys.argv[2]

send_message()

